### ISSUE TITLE
Explanation request

### ISSUE THREAD

**Issue by Bishamon1987** [yaleman/pygoodwe#119]
Hello,
Can you add a ReadMe with more information about this PyGoodWe?
How can you use it. How to get the information of the power station?
Functions like GetCurrentGeneration() or something like that.

**Comment by yaleman** [comment]
Sure, I might find some time to do that in the future - try checking out some examples in https://github.com/yaleman/pygoodwe/blob/main/test.py first please. 😄

**Comment by Bishamon1987** [comment]
Thanks!
I figured out how it works via test.py.

**Comment by yaleman** [comment]
I've added API documentation here as well, thanks for prompting me - if you have any other questions don't hesitate to ask 😄 

https://yaleman.github.io/pygoodwe/
