### ISSUE TITLE
retry has no effect on gw.getCurrentReadings(retry=1)

### ISSUE THREAD

**Issue by FabianVista** [yaleman/pygoodwe#164]
keeps repeating following message(retries are not incremented):
- Failed to call GoodWe API url='https://semsportal.com/api/v1/PowerStation/GetMonitorDetailByPowerstationId'
- no inverter data, try 1, trying again in 30 seconds

**Comment by yaleman** [comment]
I've just pushed a fix to the main branch, please try it now - that should sort it.

I'll push to pypi in a few days if it hasn't broken anything.

**Comment by FabianVista** [comment]
Thanks for the quick fix I'll give it a try as soon as possible.

**Comment by yaleman** [comment]
this got pushed yesterday for everyone to try
