### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by JB1985** [yaleman/pygoodwe#27]
Hello, 

I have a Goodwe hybrid inverter and want to use your pygoodwe. But I dont know how to use it?!

Can you please write a little HowTo?

**Comment by yaleman** [comment]
Hi there, there's some example code in [test.py](https://github.com/yaleman/pygoodwe/blob/master/test.py), or alternatively I use pygoodwe in my [goodwe2pvoutput](https://github.com/yaleman/goodwe2pvoutput/blob/master/goodwe2pvoutput/bin/goodwe2pvoutput) script which pumps data to [PVOutput.org](https://PVOutput.org)

**Comment by JB1985** [comment]
Thanks for your Script!

Do you know, how to get the data from house load and sell?

![image](https://user-images.githubusercontent.com/9932751/85127507-d8479b80-b22f-11ea-822d-bb2b9cb39c9b.png)

The other for PV and Battery i have find.

**Comment by JB1985** [comment]
The "sell" seems to be "pmeter" but I dont know how to get the data. I am trying with:

`print(json.dumps(gw.data.get('pmeter'), indent=2))`

But the output is always NULL.

**Comment by JB1985** [comment]
House load is "getLoadFlow". For "sell" -> "pmeter" i have open a pull request.

For me it works fine now!
