### ISSUE TITLE
Errors by testing pygoodwe import in IoBroker

### ISSUE THREAD

**Issue by kempert** [yaleman/pygoodwe#65]
I want import my Goodwe SEMS Data in IoBroker, so I used the work from https://forum.iobroker.net/topic/34626/goodwe-wechselrichter-und-iobroker. When im tested it following problem comes up. Im no specialist in python Syntax. 

```
pi@Raspberry-Pi4:~ $ python /home/pi/pygoodwe-master/test.py
Traceback (most recent call last):
  File "/home/pi/pygoodwe-master/test.py", line 5, in <module>
    from pygoodwe import SingleInverter, API
  File "/home/pi/pygoodwe-master/pygoodwe/__init__.py", line 19
    def __init__(self, system_id: str, account: str, password: str, **kwargs):
                                ^
SyntaxError: invalid syntax
```
I imported the master and moving the config.py.example to config.py and enter data.

Can anyone help me to use the Script?

**Comment by yaleman** [comment]
What version of Python are you using? Typically that'll mean you're using a very old one.

James

**Comment by kempert** [comment]
I have installaed follwing versions.

```
pi@Raspberry-Pi4:~ $ python --version
Python 2.7.16
pi@Raspberry-Pi4:~ $ python3 --version
Python 3.7.3
```

**Comment by yaleman** [comment]
Do you get the same error when you run "python3 /home/pi/pygoodwe-master/test.py" ?

**Comment by kempert** [comment]
oh yess that was the Problem with phyton3 it is load perfectly. THANKS

**Comment by yaleman** [comment]
Glad to see it worked out - python 2 is most definitely legacy these days :)
