### ISSUE TITLE
Problem with API

### ISSUE THREAD

**Issue by miguelsotobaez** [yaleman/pygoodwe#75]
since march i can't get this api working.

Is this API still working?

**Comment by yaleman** [comment]
It's been working for me - what errors are you getting?

**Comment by miguelsotobaez** [comment]
Its fixed right now, i dont know why, maybe a powerstation issue.

Regards.

**Comment by yaleman** [comment]
That sounds like it - if you can find some errors then I'll definitely be able to help 😄
