### ISSUE TITLE
Calls seem to fail when PV flow is 0

### ISSUE THREAD

**Issue by tywjohn** [yaleman/pygoodwe#95]
I noticed at night when there is no generation, I don't even get data for other things like inverter temperature or voltage etc.
I have yet to investigate further. Unsure if this is the API returning no data when there is no generation or whether it is pygoodwe not handling it properly.

**Comment by darylkell** [comment]
I don't know about you, but no generation = inverter is off

**Comment by tywjohn** [comment]
That may be true. Solar is a whole new world to me so I didn't realise it turns itself off like that..

**Comment by tywjohn** [comment]
A quick google search tells me you are right. Apologies.

**Comment by yaleman** [comment]
I've got a solar + battery inverter that always seems to send data, but I'm guessing solar-only ones won't.
